<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.7.31">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Ren, Hohman, and Moritz (2025)">

<title>9&nbsp; Embeddings Atlas – Paper Review: IA y Territorio</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./references.html" rel="next">
<link href="./fleischmann-2025.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-e1a5c8363afafaef2c763b6775fbf3ca.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-485d01fc63b59abcd3ee1bf1e8e2748d.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


<link rel="stylesheet" href="styles/style.css">
</head>

<body class="nav-sidebar floating slimcontent quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./urban.html">Urbanismo - IA</a></li><li class="breadcrumb-item"><a href="./ren-2025.html"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Embeddings Atlas</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Paper Review: IA y Territorio</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Prefacio</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./intro.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Introducción</span></span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./remote_sensing.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Percepción Remota - IA</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./brown-2025.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Alpha Earth Foundation</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./fang-2026.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Earth Embeddings as Products</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./urban.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Urbanismo - IA</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./han-2018.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">LLM - Urban Agents</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./agarwal-2025.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Population Dynamics - FM</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./reza-2025.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Crix - Crime and Demographics</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./fleischmann-2025.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">The Hierarchical Morphotope Classification</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ren-2025.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Embeddings Atlas</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">References</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true">
 <span class="menu-text">Appendices</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./presentaciones.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">A</span>&nbsp; <span class="chapter-title">Presentaciones</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./template_paper.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">B</span>&nbsp; <span class="chapter-title">Template</span></span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Contenidos</h2>
   
  <ul>
  <li><a href="#información-básica" id="toc-información-básica" class="nav-link active" data-scroll-target="#información-básica"><span class="header-section-number">9.1</span> Información Básica</a></li>
  <li><a href="#abstract" id="toc-abstract" class="nav-link" data-scroll-target="#abstract"><span class="header-section-number">9.2</span> Abstract</a></li>
  <li><a href="#preguntas-de-investigación-hipótesis" id="toc-preguntas-de-investigación-hipótesis" class="nav-link" data-scroll-target="#preguntas-de-investigación-hipótesis"><span class="header-section-number">9.3</span> Preguntas de Investigación / Hipótesis</a></li>
  <li><a href="#metodología" id="toc-metodología" class="nav-link" data-scroll-target="#metodología"><span class="header-section-number">9.4</span> Metodología</a>
  <ul class="collapse">
  <li><a href="#flujo-de-trabajo" id="toc-flujo-de-trabajo" class="nav-link" data-scroll-target="#flujo-de-trabajo"><span class="header-section-number">9.4.1</span> Flujo de trabajo</a></li>
  <li><a href="#modelos-algoritmos" id="toc-modelos-algoritmos" class="nav-link" data-scroll-target="#modelos-algoritmos"><span class="header-section-number">9.4.2</span> Modelos / Algoritmos</a></li>
  <li><a href="#datos" id="toc-datos" class="nav-link" data-scroll-target="#datos"><span class="header-section-number">9.4.3</span> Datos</a></li>
  <li><a href="#validación-uncertainties" id="toc-validación-uncertainties" class="nav-link" data-scroll-target="#validación-uncertainties"><span class="header-section-number">9.4.4</span> Validación &amp; Uncertainties</a></li>
  <li><a href="#replicabilidad-recursos" id="toc-replicabilidad-recursos" class="nav-link" data-scroll-target="#replicabilidad-recursos"><span class="header-section-number">9.4.5</span> Replicabilidad &amp; Recursos</a></li>
  </ul></li>
  <li><a href="#resultados-clave" id="toc-resultados-clave" class="nav-link" data-scroll-target="#resultados-clave"><span class="header-section-number">9.5</span> Resultados Clave</a></li>
  <li><a href="#discusión" id="toc-discusión" class="nav-link" data-scroll-target="#discusión"><span class="header-section-number">9.6</span> Discusión</a></li>
  <li><a href="#aplicabilidad-en-chile" id="toc-aplicabilidad-en-chile" class="nav-link" data-scroll-target="#aplicabilidad-en-chile"><span class="header-section-number">9.7</span> Aplicabilidad en Chile</a></li>
  <li><a href="#madurez-evidencia" id="toc-madurez-evidencia" class="nav-link" data-scroll-target="#madurez-evidencia"><span class="header-section-number">9.8</span> Madurez &amp; Evidencia</a></li>
  <li><a href="#impacto-en-políticas-públicas-ods" id="toc-impacto-en-políticas-públicas-ods" class="nav-link" data-scroll-target="#impacto-en-políticas-públicas-ods"><span class="header-section-number">9.9</span> Impacto en Políticas Públicas / ODS</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content page-columns page-full" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./urban.html">Urbanismo - IA</a></li><li class="breadcrumb-item"><a href="./ren-2025.html"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Embeddings Atlas</span></a></li></ol></nav>
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Embeddings Atlas</span></h1>
<p class="subtitle lead">A Scalable Approach to Clustering Embedding Projection (Apple)</p>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p><span class="citation" data-cites="ren2025scalable">Ren, Hohman, and Moritz (<a href="references.html#ref-ren2025scalable" role="doc-biblioref">2025</a>)</span> </p>
          </div>
  </div>
    
  
    
  </div>
  


</header>


<section id="información-básica" class="level2" data-number="9.1">
<h2 data-number="9.1" class="anchored" data-anchor-id="información-básica"><span class="header-section-number">9.1</span> Información Básica</h2>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Elemento</th>
<th>Detalle</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Referencia corta</strong></td>
<td><span class="citation" data-cites="ren2025scalable">Ren, Hohman, and Moritz (<a href="references.html#ref-ren2025scalable" role="doc-biblioref">2025</a>)</span> — <em>Clustering Embedding Projections</em></td>
</tr>
<tr class="even">
<td><strong>Título completo</strong></td>
<td>A Scalable Approach to Clustering Embedding Projections</td>
</tr>
<tr class="odd">
<td><strong>Revista / Volumen / DOI</strong></td>
<td><a href="https://arxiv.org/abs/2504.07285">arXiv:2504.07285v2</a> (16 May 2025). DOI: N/A</td>
</tr>
<tr class="even">
<td><strong>Temática</strong></td>
<td>Visualización de embeddings; clustering basado en densidad en 2D; escalabilidad para proyecciones (UMAP/t-SNE/PCA)</td>
</tr>
<tr class="odd">
<td><strong>Contexto / Problema</strong></td>
<td>En visualizaciones de proyecciones de embeddings (scatterplots masivos), la interpretación requiere etiquetar y resumir “regiones” o clusters. Los métodos típicos (DBSCAN/Mean Shift, etc.) operan sobre puntos y se vuelven costosos a gran escala; además pueden producir clusters que se solapan al proyectar desde alta dimensión. El paper propone clusterizar sobre un mapa de densidad 2D (KDE) en lugar de sobre los puntos.</td>
</tr>
<tr class="even">
<td><strong>Keywords</strong></td>
<td>clustering; density data; embedding projections; kernel density estimation; UMAP; visualization</td>
</tr>
<tr class="odd">
<td><strong>Code</strong></td>
<td><a href="https://github.com/apple/embedding-atlas">https://github.com/apple/embedding-atlas</a></td>
</tr>
</tbody>
</table>
</section>
<section id="abstract" class="level2" data-number="9.2">
<h2 data-number="9.2" class="anchored" data-anchor-id="abstract"><span class="header-section-number">9.2</span> Abstract</h2>
<blockquote class="blockquote">
<p><strong>Original:</strong><br>
Interactive visualization of embedding projections is a useful technique for understanding data and evaluating machine learning models. Labeling data within these visualizations is critical for interpretation, as labels provide an overview of the projection and guide user navigation. However, most methods for producing labels require clustering the points, which can be computationally expensive as the number of points grows. In this paper, we describe an efficient clustering approach using kernel density estimation in the projected 2D space instead of points. This algorithm can produce high-quality cluster regions from a 2D density map in a few hundred milliseconds, orders of magnitude faster than current approaches. We contribute the design of the algorithm, benchmarks, and applications that demonstrate the utility of the algorithm, including labeling and summarization.</p>
</blockquote>
<blockquote class="blockquote">
<p><strong>Traducción al español:</strong><br>
La visualización interactiva de proyecciones de embeddings es una técnica útil para comprender datos y evaluar modelos de aprendizaje automático. El etiquetado de datos dentro de estas visualizaciones es crítico para la interpretación, ya que las etiquetas brindan una visión general de la proyección y guían la navegación del usuario. Sin embargo, la mayoría de los métodos para producir etiquetas requieren clusterizar los puntos, lo que puede ser computacionalmente costoso a medida que crece el número de puntos. En este artículo describimos un enfoque eficiente de clustering que utiliza estimación de densidad por kernel (KDE) en el espacio 2D proyectado, en lugar de operar sobre los puntos. Este algoritmo puede producir regiones de clusters de alta calidad a partir de un mapa de densidad 2D en unos pocos cientos de milisegundos, órdenes de magnitud más rápido que los enfoques actuales. Contribuimos con el diseño del algoritmo, benchmarks y aplicaciones que demuestran su utilidad, incluyendo etiquetado y resumen.</p>
</blockquote>
</section>
<section id="preguntas-de-investigación-hipótesis" class="level2" data-number="9.3">
<h2 data-number="9.3" class="anchored" data-anchor-id="preguntas-de-investigación-hipótesis"><span class="header-section-number">9.3</span> Preguntas de Investigación / Hipótesis</h2>
<ul>
<li>¿Puede un algoritmo de clustering que opera sobre un mapa de densidad 2D (KDE) generar regiones de clusters “de calidad” para proyecciones de embeddings, manteniendo coherencia visual con la percepción humana? <em>(inferida)</em><br>
</li>
<li>¿Qué ganancias de rendimiento (tiempo) se obtienen al clusterizar densidad 2D en vez de puntos, en datasets desde decenas de miles hasta millones de elementos, manteniendo resultados comparables a métodos escalables basados en puntos? <em>(inferida)</em></li>
</ul>
</section>
<section id="metodología" class="level2 page-columns page-full" data-number="9.4">
<h2 data-number="9.4" class="anchored" data-anchor-id="metodología"><span class="header-section-number">9.4</span> Metodología</h2>
<section id="flujo-de-trabajo" class="level3 page-columns page-full" data-number="9.4.1">
<h3 data-number="9.4.1" class="anchored" data-anchor-id="flujo-de-trabajo"><span class="header-section-number">9.4.1</span> Flujo de trabajo</h3>
<ol type="1">
<li>Proyectar embeddings de alta dimensión a 2D (p.ej., UMAP con distancia coseno).<br>
</li>
<li>Construir un mapa de densidad 2D de la proyección mediante KDE (con técnicas eficientes de binning/aproximación; el paper reporta un cómputo de KDE en GPU/WebGL).<br>
</li>
<li>Clusterizar el <strong>mapa de densidad</strong> (pixeles) usando un procedimiento en tres etapas: (i) división en regiones por “hill-climbing” hacia máximos locales, (ii) fusión (union) de regiones “triviales” cercanas a bordes, y (iii) truncamiento por umbral relativo de densidad para limpiar límites.<br>
</li>
<li>(Post-proceso) Convertir el mapa de clusters a polígonos (p.ej., con un trazado tipo Suzuki) para visualización y/o consultas.<br>
</li>
<li>(Aplicación demostrada) Generar etiquetas por cluster: aproximar polígonos por rectángulos no solapados y traducirlos a consultas SQL; aplicar c-TF-IDF para etiquetas en texto.</li>
</ol>
<div class="quarto-figure quarto-figure-center page-columns page-full">
<figure class="figure page-columns page-full">
<p><img src="images/ren-explanation.png" class="img-fluid figure-img" width="800"></p>
<figcaption class="margin-caption">Explicación del Algoritmo</figcaption>
</figure>
</div>
</section>
<section id="modelos-algoritmos" class="level3 page-columns page-full" data-number="9.4.2">
<h3 data-number="9.4.2" class="anchored" data-anchor-id="modelos-algoritmos"><span class="header-section-number">9.4.2</span> Modelos / Algoritmos</h3>
<ul>
<li>Proyección: UMAP (mencionado explícitamente en ejemplos) con distancia coseno.<br>
</li>
<li>Densidad: KDE 2D sobre la proyección (implementación reportada en GPU/WebGL para benchmarking).<br>
</li>
<li>Clustering propuesto (sobre densidad):
<ul>
<li><strong>Inicialización por máximos locales</strong>: cada píxel asciende al vecino de mayor densidad hasta un máximo local; agrupa píxeles por máximo alcanzado (disjoint set / union-find).<br>
</li>
<li><strong>Fusión de clusters</strong>: usando un grafo de vecindad entre regiones; criterio: si el máximo local del cluster está muy cerca del borde, fusionar con el vecino correspondiente (greedy por prioridad).<br>
</li>
<li><strong>Truncamiento</strong>: eliminar píxeles con densidad menor a <em>dmin(c) = max_density(c) × factor</em> (factor 0.1 en el paper).<br>
</li>
</ul></li>
<li>Baselines comparados: supercluster (Mapbox; variante rápida tipo DBSCAN), y discusión de DBSCAN/HDBSCAN/OPTICS/Mean Shift (scikit-learn) como demasiado lentos en su setting.</li>
</ul>
<div class="quarto-figure quarto-figure-center page-columns page-full">
<figure class="figure page-columns page-full">
<p><img src="images/ren-algorithm.png" class="img-fluid figure-img" width="400"></p>
<figcaption class="margin-caption">Pseudo Código del Algoritmo</figcaption>
</figure>
</div>
</section>
<section id="datos" class="level3" data-number="9.4.3">
<h3 data-number="9.4.3" class="anchored" data-anchor-id="datos"><span class="header-section-number">9.4.3</span> Datos</h3>
<p>El trabajo evalúa el algoritmo sobre proyecciones 2D de embeddings en tres datasets representativos, cubriendo texto e imágenes y escalas desde 63k hasta 1.28M puntos. Los embeddings se proyectan (ejemplos) con UMAP y distancia coseno, luego se estima un mapa de densidad (e.g., 1000×1000 píxeles) sobre el cual se ejecuta el clustering. Además, para demostrar utilidad en etiquetado, se usa UltraChat-200k y se generan etiquetas por cluster mediante consultas SQL y c-TF-IDF en un entorno web (DuckDB WebAssembly).</p>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Tipo</th>
<th>Fuente</th>
<th>Cobertura temporal</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Imágenes (ImageNet-1k; 1.28M puntos)</td>
<td>ImageNet Large Scale Visual Recognition Challenge</td>
<td>N/A</td>
</tr>
<tr class="even">
<td>Texto (ACL Abstracts; 63k puntos)</td>
<td>Colección de abstracts ACL (referenciada en el paper)</td>
<td>N/A</td>
</tr>
<tr class="odd">
<td>Texto conversacional (UltraChat-200k; 200k puntos)</td>
<td>HuggingFace (UltraChat-200k)</td>
<td>N/A</td>
</tr>
</tbody>
</table>
</section>
<section id="validación-uncertainties" class="level3 page-columns page-full" data-number="9.4.4">
<h3 data-number="9.4.4" class="anchored" data-anchor-id="validación-uncertainties"><span class="header-section-number">9.4.4</span> Validación &amp; Uncertainties</h3>
<p>La evaluación se centra en (i) <strong>rendimiento</strong> (tiempo de clustering) sobre tres datasets, (ii) <strong>calidad</strong> mediante comparación visual/cualitativa con un baseline escalable (supercluster), y (iii) <strong>utilidad</strong> demostrando un pipeline de etiquetado y resumen de clusters (c-TF-IDF vía SQL). No se reportan métricas estándar de “calidad de clustering” (p.ej., NMI/ARI/silhouette) ni validación cuantitativa de etiquetas; el énfasis es pragmático (interactividad, velocidad, resultados visualmente comparables).</p>
<div class="quarto-figure quarto-figure-center page-columns page-full">
<figure class="figure page-columns page-full">
<p><img src="images/ren-eval.png" class="img-fluid figure-img" width="400"></p>
<figcaption class="margin-caption">Comparación del Algoritmo propuesto con <a href="https://blog.mapbox.com/clustering-millions-of-points-on-a-map-with-supercluster-272046ec5c97">Supercluster de Mapbox</a>.</figcaption>
</figure>
</div>
<table class="caption-top table">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th>Métrica</th>
<th>Valor</th>
<th>Alcance</th>
<th>Notas</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Tiempo de clustering (Ours)</td>
<td>55 ms</td>
<td>ACL Abstracts (63k puntos)</td>
<td>Sobre mapa de densidad 1000×1000.</td>
</tr>
<tr class="even">
<td>Tiempo de clustering (Ours)</td>
<td>52 ms</td>
<td>UltraChat-200k (200k puntos)</td>
<td>Sobre mapa de densidad 1000×1000.</td>
</tr>
<tr class="odd">
<td>Tiempo de clustering (Ours)</td>
<td>55 ms</td>
<td>ImageNet-1k (1.28M puntos)</td>
<td>Sobre mapa de densidad 1000×1000; número de puntos es irrelevante una vez estimada la densidad.</td>
</tr>
<tr class="even">
<td>Tiempo KDE (GPU/WebGL)</td>
<td>+41 ms</td>
<td>ACL Abstracts</td>
<td>Reportado como tiempo adicional para calcular KDE desde puntos 2D.</td>
</tr>
<tr class="odd">
<td>Tiempo KDE (GPU/WebGL)</td>
<td>+32 ms</td>
<td>UltraChat-200k</td>
<td>Reportado como tiempo adicional para calcular KDE desde puntos 2D.</td>
</tr>
<tr class="even">
<td>Tiempo KDE (GPU/WebGL)</td>
<td>+35 ms</td>
<td>ImageNet-1k</td>
<td>Reportado como tiempo adicional para calcular KDE desde puntos 2D.</td>
</tr>
<tr class="odd">
<td>Tiempo supercluster</td>
<td>269 ms</td>
<td>ACL Abstracts</td>
<td>Clustering sobre puntos 2D.</td>
</tr>
<tr class="even">
<td>Tiempo supercluster</td>
<td>913 ms</td>
<td>UltraChat-200k</td>
<td>Clustering sobre puntos 2D.</td>
</tr>
<tr class="odd">
<td>Tiempo supercluster</td>
<td>5611 ms</td>
<td>ImageNet-1k</td>
<td>Clustering sobre puntos 2D.</td>
</tr>
<tr class="even">
<td>Tiempo total (clustering+KDE)</td>
<td>~80–100 ms</td>
<td>General</td>
<td>El paper sugiere que este rango podría ser usable en aplicaciones interactivas.</td>
</tr>
<tr class="odd">
<td>Etiquetado (c-TF-IDF vía SQL)</td>
<td>~36 s</td>
<td>UltraChat-200k</td>
<td>Generación de etiquetas para 250 clusters (con dos niveles de zoom) usando DuckDB WASM.</td>
</tr>
</tbody>
</table>
</section>
<section id="replicabilidad-recursos" class="level3" data-number="9.4.5">
<h3 data-number="9.4.5" class="anchored" data-anchor-id="replicabilidad-recursos"><span class="header-section-number">9.4.5</span> Replicabilidad &amp; Recursos</h3>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Ítem</th>
<th>Sí/No</th>
<th>Detalle</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Código disponible</td>
<td>Sí</td>
<td>Implementación open-source: embedding-atlas (Apple) en GitHub.</td>
</tr>
<tr class="even">
<td>Datos disponibles</td>
<td>Sí</td>
<td>Datasets mencionados son públicos (ImageNet-1k, ACL Abstracts, UltraChat-200k).</td>
</tr>
<tr class="odd">
<td>Parámetros reproducibles</td>
<td>Parcial</td>
<td>Se describen factores clave (p.ej., umbral 0.1 para truncamiento); detalles completos de KDE/bandwidth y configuración de proyección pueden requerir revisar código/demo.</td>
</tr>
<tr class="even">
<td>Implementación descrita</td>
<td>Sí</td>
<td>Rust + compilación a WebAssembly para uso web; KDE reportado con GPU/WebGL en benchmarks.</td>
</tr>
<tr class="odd">
<td>Demo / herramienta</td>
<td>Sí</td>
<td>Se menciona demo interactivo y viewer web para etiquetado (DuckDB WebAssembly).</td>
</tr>
</tbody>
</table>
</section>
</section>
<section id="resultados-clave" class="level2" data-number="9.5">
<h2 data-number="9.5" class="anchored" data-anchor-id="resultados-clave"><span class="header-section-number">9.5</span> Resultados Clave</h2>
<ul>
<li>El algoritmo clusteriza un mapa de densidad 2D de 1000×1000 en ~52–55 ms en tres datasets (63k, 200k, 1.28M puntos), con complejidad dominada por el número de píxeles, no por el número de puntos.<br>
</li>
<li>En comparación, supercluster tarda 269 ms (63k), 913 ms (200k) y 5611 ms (1.28M). A escala 200k, el paper reporta ~10× de mejora en velocidad con calidad visual similar.<br>
</li>
<li>Incluyendo el cálculo de KDE en GPU/WebGL, el tiempo combinado reportado es ~80–100 ms, apuntando a uso interactivo.<br>
</li>
<li>En la demostración de etiquetado, generar etiquetas c-TF-IDF por SQL para ~250 clusters (2 niveles de zoom) en UltraChat-200k toma ~36 s (costo del resumen/etiquetado, no del clustering).</li>
</ul>
</section>
<section id="discusión" class="level2" data-number="9.6">
<h2 data-number="9.6" class="anchored" data-anchor-id="discusión"><span class="header-section-number">9.6</span> Discusión</h2>
<ul>
<li><strong>Contribuciones:</strong>
<ul>
<li>Propone un método rápido y escalable para clustering en proyecciones de embeddings operando en densidad 2D (KDE) en lugar de puntos.<br>
</li>
<li>Describe el algoritmo (regiones por máximos locales + fusión + truncamiento), análisis de complejidad y benchmarks comparativos.<br>
</li>
<li>Muestra aplicaciones para etiquetado y resumen: polígonos → consultas SQL → c-TF-IDF.<br>
</li>
</ul></li>
<li><strong>Limitaciones:</strong>
<ul>
<li>Produce una lista plana de clusters (sin jerarquía explícita); para multiescala se sugiere ejecutar con múltiples bandwidths, pero sin relación jerárquica formal.<br>
</li>
<li>No incorpora metadatos categóricos (solo clusteriza un mapa de densidad único).<br>
</li>
<li>Está limitado al espacio proyectado 2D: puede alinearse con percepción humana, pero no garantiza fidelidad a clusters en alta dimensión.<br>
</li>
</ul></li>
<li><strong>Futuro:</strong>
<ul>
<li>Desarrollar clustering jerárquico multiescala con relaciones consistentes entre niveles.<br>
</li>
<li>Extender el método para considerar variables categóricas/metadata al formar clusters.</li>
</ul></li>
</ul>
</section>
<section id="aplicabilidad-en-chile" class="level2" data-number="9.7">
<h2 data-number="9.7" class="anchored" data-anchor-id="aplicabilidad-en-chile"><span class="header-section-number">9.7</span> Aplicabilidad en Chile</h2>
<table class="caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>Aspecto</th>
<th>Evaluación</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Exploración territorial con embeddings</td>
<td>Alta: útil para explorar grandes colecciones de embeddings (p.ej., parches de imágenes satelitales de Chile, POIs, <strong>Delitos</strong>), proyectarlas a 2D y generar regiones/etiquetas rápidamente para análisis exploratorio.</td>
</tr>
<tr class="even">
<td>Integración con SIG / consultas espaciales</td>
<td>Media–Alta: los clusters como polígonos 2D facilitan consultas tipo “range query” y agregación; habría que mapear estos polígonos al contexto SIG (nota: son polígonos en el espacio de proyección, no geográficos).</td>
</tr>
<tr class="odd">
<td>Interpretabilidad para tomadores de decisión</td>
<td>Media: mejora navegación/overview y permite etiquetado; sin embargo, la interpretación depende de la calidad del embedding/proyección y de la semántica del etiquetado (especialmente en dominios territoriales).</td>
</tr>
<tr class="even">
<td>Riesgos / sesgos</td>
<td>Media: al operar en 2D, la proyección puede distorsionar relaciones; los clusters reflejan estructura proyectada, no necesariamente estructura “real” del fenómeno territorial.</td>
</tr>
<tr class="odd">
<td>Costos de adopción</td>
<td>Baja–Media: código abierto y orientado a web (Rust/WASM), pero requiere pipeline de embeddings + proyección + KDE y (si se desea) infraestructura de etiquetado/DB.</td>
</tr>
</tbody>
</table>
</section>
<section id="madurez-evidencia" class="level2" data-number="9.8">
<h2 data-number="9.8" class="anchored" data-anchor-id="madurez-evidencia"><span class="header-section-number">9.8</span> Madurez &amp; Evidencia</h2>
<table class="caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>Eje</th>
<th>Nivel</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Evidencia empírica (benchmarks)</td>
<td>Media–Alta</td>
</tr>
<tr class="even">
<td>Escalabilidad / rendimiento</td>
<td>Alta</td>
</tr>
<tr class="odd">
<td>Validación de calidad de clustering</td>
<td>Media (principalmente cualitativa vs.&nbsp;baseline)</td>
</tr>
<tr class="even">
<td>Disponibilidad de implementación</td>
<td>Alta (open-source)</td>
</tr>
<tr class="odd">
<td>Transferibilidad a dominios territoriales</td>
<td>Media (requiere embeddings/proyecciones adecuadas)</td>
</tr>
</tbody>
</table>
</section>
<section id="impacto-en-políticas-públicas-ods" class="level2" data-number="9.9">
<h2 data-number="9.9" class="anchored" data-anchor-id="impacto-en-políticas-públicas-ods"><span class="header-section-number">9.9</span> Impacto en Políticas Públicas / ODS</h2>
<blockquote class="blockquote">
<p>Potencial habilitador (indirecto): al acelerar la clusterización y el etiquetado de proyecciones de embeddings, el enfoque puede facilitar sistemas de análisis exploratorio para grandes repositorios de datos relevantes para políticas públicas (p.ej., monitoreo ambiental, clasificación de reportes ciudadanos, análisis de documentos normativos). Su contribución es metodológica/infraestructural (visual analytics) más que un caso aplicado a un ODS específico, por lo que el impacto depende del caso de uso que se implemente (p.ej., ODS 11 ciudades sostenibles, ODS 13 acción por el clima, ODS 15 vida de ecosistemas terrestres).</p>
</blockquote>


<div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" role="list" style="display: none">
<div id="ref-ren2025scalable" class="csl-entry" role="listitem">
Ren, Donghao, Fred Hohman, and Dominik Moritz. 2025. <span>“A Scalable Approach to Clustering Embedding Projections.”</span> <em>arXiv Preprint arXiv:2504.07285</em>.
</div>
</div>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
        const codeEl = trigger.previousElementSibling.cloneNode(true);
        for (const childEl of codeEl.children) {
          if (isCodeAnnotation(childEl)) {
            childEl.remove();
          }
        }
        return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./fleischmann-2025.html" class="pagination-link" aria-label="The Hierarchical Morphotope Classification">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">The Hierarchical Morphotope Classification</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./references.html" class="pagination-link" aria-label="References">
        <span class="nav-page-text">References</span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>Copyright 2025, Denis Berroeta</p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    </div>
    <div class="nav-footer-right">
      &nbsp;
    </div>
  </div>
</footer>




</body></html>